# site settings
title: devergence
subtitle: estudio independiente de desarrollo
email: contacto@devergence.com
description: Una marca bajo la que materializar las ideas fascinantes<br /> que nos motivaron a dedicarnos a este oficio.
baseurl: "/devergence.web" # the subpath of your site, e.g. /blog
url: http://www.devergence.com # the base hostname & protocol for your site
author:
street_address: 
city: Madrid
state: ES
zip_code: 28918
country: España
phone:

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/devergence_std

# build settings
markdown: kramdown

sass:
  style: compressed
